site_name: Administración de Sistemas Operativos
site_url: https://fjavier-hernandez.github.io/aso/
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "1.- UD1. ShellScripting":
    - "01_ShellScripting/ProgramacionAula.md"
    - "01_ShellScripting/ResumenUD.md"
    - "1.1- Introducción": "01_ShellScripting/011_ShellScript_Intro.md"
    - "1.2- Sintaxis": "01_ShellScripting/012_ShelScript_Sintaxis.md"
    - "1.3- Control de flujo": "01_ShellScripting/013_ShellScript_ControlFlujo.md"
    - "1.4- Vectores y Funciones": "01_ShellScripting/014_ShellScript_VectoresFunciones.md"
    - "1.5- Refuerzo y ampliación": "01_ShellScripting/015_ShellScript_RefuerzoAmpliacion.md"
    - "1.6- Prueba Auditoria": "01_ShellScripting/016_ShellScript_PruebaEspecifica.md"
    # - "1.3- Docker": "013_Docker.md"
  - "2.- UD2: PowerShell":
    - "02_PowerShell/ProgramacionAula.md"
    - "2.1- Introducción": "02_PowerShell/021_IntroducciónPwSh.md"
    - "2.2- Sintaxis": "02_PowerShell/022_PowerShell_Sintaxis.md"
    - "2.3- Control de flujo": "02_PowerShell/023_PowerShell_ControlFlujo.md"
    - "2.4- Vectores y Funciones": "02_PowerShell/024_PowerShell_VectoresFunciones.md"
  - "3.- UD3: Administración de procesos del sistema":
    - "03_Procesos/ProgramacionAula.md"
    - "3.1- Introducción Procesos, Planificador": "03_Procesos/031_Planificador.md"
    - "3.2- Hilos, Sincronización e interrupciones, Herramientas gráficas": "03_Procesos/032_Hilos.md"
    - "3.3- Gestión de procesos en Shell de Linux.": "03_Procesos/033_GestionProcesosShell.md"
    - "3.4- Gestión de procesos en PowerShell.": "03_Procesos/034_GestionProcesosPWSH.md"
    - "3.5- Arranque del sistema. Servicios. Systemd.": "03_Procesos/035_ArranqueServicios.md"
  - "4.- Servicios de Directorio Libres: LDAP":
      - "04_LDAP/ProgramacionAula.md"
      - "4.1- Introducción Servicios de directorio y LDAP": "04_LDAP/041_Introduccion_SDyLDAP.md"
      - "4.2- Instalación y configuración de OpenLDAP": "04_LDAP/042_InstalacionConfigLDAP_PR.md"
      - "4.3- Modelo de Información de LDAP": "04_LDAP/043_LDAP_DIT.md"
      - "4.4- Creación y comprobación de Usuarios/Grupos OpenLDAP": "04_LDAP/044_UsersLDAP.md"
      - "4.5- Esquema LDAP": "04_LDAP/045_LDAP_EsquemaHerramientas.md"
      - "4.6- Gestión usuarios LDAP con GUI": "04_LDAP/046_LDAP_Graficas.md"
  - "5.- Servicios de Directorio Propietarios: Active Directory":
      - "5.1- Introducción Active Directory": "05_AD/051_ActiveDirectory.md"


  
  #- "4.- Información del sistema":
    #- "4.1- Estructura de directorios": "041_EstructuraDirectorios.md" 
    #- "4.2- VFS, Sw Instalado y Gestión Rendimiento": "042_ArchivosVirtualSWinstaladoRendimiento.md"
    #- "4.3- Planificación de Tareas": "043_PlanificaciónTareas.md"
  #- "5.- Servicios de acceso y administración remota":
    #- "5.1- Acceso Remoto en modo texto": "051_AccesoRemotoLinux.md"
    #- "5.2- Escritorio Remoto": "052_EscritorioRemoto.md"
    #- "5.3- Herramientas gráficas externas.": "053_HerramientasGraficAdminRemota.md"
  #- "6.- Administración de Servidores de Impresión":
    #- "6.1- Servidores de Impresión": "061_ServidoresImpresion.md"
    #- "6.2- Servidor de impresión en GNU/Linux": "062_ServidoresImpresionLinux.md"
    #- "6.3- Servidor de impresión en Windows Server": "063_ServidorImpresionWindowsServer.md"
  #- "7.- Integración de sistemas operativos en red libres y propietarios":
    #- "7.1- Servicios de red para compartir recursos": "071_ServiciosRedRecursosCompartidos.md"
    #- "7.2- Samba": "072_Samba.md"
    #- "7.3- NFS": "073_NFS.md"
    #- "7.4- NextCloud": "074_NextCloud.md"
  
#  - "": ""

theme:
  language: es
  favicon: imagenes/favicon.png
  name: "material"
  palette:
    - scheme: javi
      #primary: light blue
      #accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate 
      #primary: light blue
      #accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo día
  font:
    text: Roboto
    code: Roboto Mono
  logo: "./imagenes/logofp.png"
  features:
    - header.autohide
    - toc.integrate
    - navigation.indexes
extra_css:
  - stylesheets/extra.css

extra:
  search:
    language: "es"
  social:
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/aitormedrano
    - icon: fontawesome/solid/envelope-square
      link: mailto:<fj.hernandez@edu.gva.es>
  analytics:
    provider: google
    property: G-0CPJP88MBF

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2021-2022 Fº Javier Hernández - Licencia CC BY-NC-SA

