site_name: Administración de Sistemas Operativos
site_url: https://javierhernadez81.github.io/aso2122/
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "1.- UD1: ShellScripting":
    - 01_ShellScripting/index.md
    - "1.1- Introducción": "01_ShellScripting/011_ShellScript_Intro.md"
    - "1.2- Sintaxis": "01_ShellScripting/012_ShelScript_Sintaxis.md"
    - "1.3- Control de flujo": "01_ShellScripting/013_ShellScript_ControlFlujo.md"
    - "1.4- Vectores y funciones": "01_ShellScripting/014_ShellScript_VectoresFunciones.md"
    - "1.5- Refuerzo y ampliación": "01_ShellScripting/015_ShellScript_RefuerzoAmpliacion.md"
    - "1.6- Prueba Específica": "01_ShellScripting/016_ShellScript_PruebaEspecifica.md"
    #- "1.2- PowerShell": "012_PowerShell.md"
    #- "1.3- Docker": "013_Docker.md"
  - "2.- UD2: PowerShell":
    - 02_PowerShell/index.md
    - "2.1- PowerShell": "02_PowerShell/012_PowerShell.md"  
  - "2.- Administración de servicios de directorio":
    - "2.1- Introducción de servicios de directorio": "021_Introduccion_SD.md"
    - "2.2- LDAP": "022_LDAP.md"
    - "2.3- Active Directory": "023_ActiveDirectory.md"
  - "3.- Administración de procesos del sistema":
    - "3.1- Planificación y sincronización de procesos": "031_Planificador.md"
    - "3.2- Gestión de los procesos del sistema": "032_GestionProcesos.md"
    - "3.3- Secuencia de arranque del sistema. Demonios y servicios": "033_ArranqueServicios.md"
  - "4.- Información del sistema":
    - "4.1- Estructura de directorios": "041_EstructuraDirectorios.md" 
    - "4.2- VFS, Sw Instalado y Gestión Rendimiento": "042_ArchivosVirtualSWinstaladoRendimiento.md"
    - "4.3- Planificación de Tareas": "043_PlanificaciónTareas.md"
  - "5.- Servicios de acceso y administración remota":
    - "5.1- Acceso Remoto en modo texto": "051_AccesoRemotoLinux.md"
    - "5.2- Escritorio Remoto": "052_EscritorioRemoto.md"
    - "5.3- Herramientas gráficas externas.": "053_HerramientasGraficAdminRemota.md"
  - "6.- Administración de Servidores de Impresión":
    - "6.1- Servidores de Impresión": "061_ServidoresImpresion.md"
    - "6.2- Servidor de impresión en GNU/Linux": "062_ServidoresImpresionLinux.md"
    - "6.3- Servidor de impresión en Windows Server": "063_ServidorImpresionWindowsServer.md"
  - "7.- Integración de sistemas operativos en red libres y propietarios":
    - "7.1- Servicios de red para compartir recursos": "071_ServiciosRedRecursosCompartidos.md"
    - "7.2- Samba": "072_Samba.md"
    - "7.3- NFS": "073_NFS.md"
    - "7.4- NextCloud": "074_NextCloud.md"
  
#  - "": ""

theme:
  language: es
  favicon: imagenes/favicon.png
  name: "material"
  palette:
    - scheme: javi
      #primary: light blue
      #accent: "Teal"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo noche
    - scheme: slate 
      #primary: light blue
      #accent: "Teal"
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo día
  font:
    text: Roboto
    code: Roboto Mono
  logo: "imagenes/logofp.png"
  features:
    - header.autohide
    - toc.integrate
    - navigation.indexes
extra_css:
  - stylesheets/extra.css

extra:
  search:
    language: "es"
  social:
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/aitormedrano
    - icon: fontawesome/solid/envelope-square
      link: mailto:<fj.hernandez@edu.gva.es>
  analytics:
    provider: google
    property: G-0CPJP88MBF

plugins:
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3

copyright: 2021-2022 Fº Javier Hernández - Licencia CC BY-NC-SA

